### ISSUE TITLE
Cannot open load file" "No such file or directory" "tablist"

### ISSUE THREAD

**Issue by yibie** [krisbalintona/denote-interface#1]
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "tablist")
  require(tablist)
  load-with-code-conversion("/Users/chenyibin/.emacs.d/elpaca/builds/denote-zettel-interface/denote-zettel-interface.el" "/Users/chenyibin/.emacs.d/elpaca/builds/denote-zettel-interface/denote-zettel-interface.el" t t)
  require(denote-zettel-interface nil t)
  (not (require 'denote-zettel-interface nil t))
  (if (not (require 'denote-zettel-interface nil t)) (display-warning 'use-package (format "Cannot load %s" 'denote-zettel-interface) :error))
  (condition-case err (if (not (require 'denote-zettel-interface nil t)) (display-warning 'use-package (format "Cannot load %s" 'denote-zettel-interface) :error)) ((debug error) (funcall use-package--warning73 :catch err)))
  (condition-case-unless-debug err (if (not (require 'denote-zettel-interface nil t)) (display-warning 'use-package (format "Cannot load %s" 'denote-zettel-interface) :error)) (error (funcall use-package--warning73 :catch err)))

**Comment by krisbalintona** [comment]
Ah, yeah, tablist.el is a dependency. I added some explicit installation instructions in the README: https://github.com/krisbalintona/denote-zettel-interface?tab=readme-ov-file#installation
