### ISSUE TITLE
Mention your package in the Denote manual?

### ISSUE THREAD

**Issue by protesilaos** [krisbalintona/denote-interface#2]
Hello @krisbalintona!

The Denote manual mentions some of the packages that extend Denote. Do you want to have yours there as well? I can write the entry or you can prepare a pull request: whatever works for you.

**Comment by krisbalintona** [comment]
Hi @protesilaos!

I'm pleasantly surprised to receive your offer. Yes, I think at least a few users would find discovering this project useful. Would you like me to prepare a small blurb, or are you able to write one yourself based on the current README? I put the README together somewhat quickly so if you'd like more detail I can supply them.

However, it might be relevant to know that I currently only plan to add this project to an official repository if I notice at least a few other users finding good mileage from it.

**Comment by protesilaos** [comment]
Hello @krisbalintona! I had some technical problems with my email setup. Long story short: it works now. I will update the Denote manual tomorrow. Then you can review it and decide if you want to add something else (and you are welcome to do so).

**Comment by krisbalintona** [comment]
@protesilaos No problem. Thanks for the update.

I'll keep an eye out for the update in the next few days. I'll close this issue for now. In case I have suggestions for changing the description, I'll create an issue/PR in Denote's repo; if you don't hear from me, assume that I'm happy with it. Thank you!
